name: lab - E2 - Environments

on: push

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Dev Stage deployed"

  prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: echo "Deploying to Prod"
