name: Lab B1 - Execution flow

#the github action command,expecting job to execute on this action
on: push

#there is a job to be executed, runs on latest(SaaS runner, & hello world sample)
jobs:
  lifecycle:
    runs-on: ubuntu-latest
    steps:
      - run: uname -a
      - run: echo "I love Stacey"
      - run: pwd
      - run: hostname

